[[redirects]]
  from = "/kubernetes/charmed-k8s/docs/*"
  to = "/:splat"
  status = 200
  force = false

# COMMENT: This a rule for managed kubernetes
[[redirects]]
  from = "/kubernetes/managed"
  to = "https://www.ubuntu.com/kubernetes/managed"
  status = 200
  force = false

 # COMMENT: This a rule for support
[[redirects]]
  from = "/support"
  to = "https://www.ubuntu.com/support"
  status = 200
  force = false
