---
wrapper_template: "kubernetes/docs/base_docs.html"
markdown_includes:
  nav: "kubernetes/docs/shared/_side-navigation.md"
context:
  title: "kubeapi-load-balancer charm"
  description: Etcd Charm reference
keywords: kubeapi-load-balancer, charm, config
tags: [reference]
sidebar: k8smain-sidebar
permalink: charm-kubeapi-load-balancer.html
layout: [base, ubuntu-com]
toc: False
---

The `kubeapi-load-balancer` charm xxxxxxxxxxxxxxxx xx x xxxxxxxxxxxxxxxxx
xxx xx xxx xxxx xxx xxxxxx xx xxxxxx xxxxx xxxxxx xxxxx xxx

## kubeapi-load-balancer charm configuration

<!-CONFIG TABLE->
<!-DO NOT EDIT - THIS SECTION IS AUTOGENERATED ->

<!- CONFIG ENDS->


## kubeapi-load-balancer charm actions


## <Specific topics, etc>
